// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB42OzLWiZAApgOwiOLAoDVSppl0npKCEo',
    appId: '1:738224363416:web:e2483bc8eac2f5cba13ded',
    messagingSenderId: '738224363416',
    projectId: 'note-app-7701c',
    authDomain: 'note-app-7701c.firebaseapp.com',
    storageBucket: 'note-app-7701c.firebasestorage.app',
    measurementId: 'G-VHKYYNVYPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlT-absWGVdPFRZeZ59pEc1LydWTqzWkg',
    appId: '1:738224363416:android:6be648198a4e8919a13ded',
    messagingSenderId: '738224363416',
    projectId: 'note-app-7701c',
    storageBucket: 'note-app-7701c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB42OzLWiZAApgOwiOLAoDVSppl0npKCEo',
    appId: '1:738224363416:web:e0d699ba81adc33da13ded',
    messagingSenderId: '738224363416',
    projectId: 'note-app-7701c',
    authDomain: 'note-app-7701c.firebaseapp.com',
    storageBucket: 'note-app-7701c.firebasestorage.app',
    measurementId: 'G-Y7LDBTYM8D',
  );

}