// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEfQ4NvFhof_Cq_CZjntFvVH2QRBHkJJs',
    appId: '1:895746574423:web:bbf57aa240c9d60890fb12',
    messagingSenderId: '895746574423',
    projectId: 'flutter-firebase-mastery-2023',
    authDomain: 'flutter-firebase-mastery-2023.firebaseapp.com',
    storageBucket: 'flutter-firebase-mastery-2023.firebasestorage.app',
    measurementId: 'G-W9MLPBC5HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFXLkvW4j4O6Eq55L272gzBD0YJTE9CmQ',
    appId: '1:895746574423:android:18409cb2407372d190fb12',
    messagingSenderId: '895746574423',
    projectId: 'flutter-firebase-mastery-2023',
    storageBucket: 'flutter-firebase-mastery-2023.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEfQ4NvFhof_Cq_CZjntFvVH2QRBHkJJs',
    appId: '1:895746574423:web:a75d0a818ac914da90fb12',
    messagingSenderId: '895746574423',
    projectId: 'flutter-firebase-mastery-2023',
    authDomain: 'flutter-firebase-mastery-2023.firebaseapp.com',
    storageBucket: 'flutter-firebase-mastery-2023.firebasestorage.app',
    measurementId: 'G-J6VRLH5F80',
  );
}
